### ISSUE TITLE
PHP 8.0 Build Problems on macOS

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/nginx-php-docker#26]
We are getting the following when trying to build on macOS and PHP 8.

```
#5 47.07 ./minilua /usr/src/php/ext/opcache/jit/dynasm/dynasm.lua  -D X64=1 -o jit/zend_jit_x86.c /usr/src/php/ext/opcache/jit/zend_jit_x86.dasc
#5 48.89 make: Circular jit/zend_jit.lo <- jit/zend_jit.lo dependency dropped.
#5 48.89 /bin/sh /usr/src/php/ext/opcache/libtool --mode=compile cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/jit/zend_jit.c -o jit/zend_jit.lo 
#5 48.93 mkdir jit/.libs
#5 48.93  cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/jit/zend_jit.c  -fPIC -DPIC -o jit/.libs/zend_jit.o
#5 139.2 cc: fatal error: Killed signal terminated program cc1
#5 139.2 compilation terminated.
#5 139.2 make: *** [Makefile:299: jit/zend_jit.lo] Error 1
```

**Comment by Justintime50** [comment]
This was actually magically fixed after waiting many days and rebuilding, maybe something with a newer version of PHP8 got fixed or some bad cache cleared out.

**Comment by tiefenb** [comment]
This happens still sometimes on my side :-(

**Comment by Justintime50** [comment]
Thanks for bringing this up @tiefenb! Can you elaborate and give me some more details so I can try to reproduce? Things that may be helpful:

1. macOS version/computer specs used
2. What version of this image you're trying to build (v1-v9)
3. Is it the PHP 8.0 image?
4. What version of Docker are you using?
5. Does this error still occur if you try building against the v9 version of the PHP8 image?

I'll reopen the issue for now and see if I can't reproduce it.

**Comment by tiefenb** [comment]
Ah sorry, I'm using the official PHP Docker file.

- 1 GB Memory / 1 AMD vCPU / 25 GB Disk + 5 GB / FRA1 - Ubuntu 20.04 (LTS) x64 (on Digital Ocean)
- php:8.1.4-fpm-bullseye
- Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

**Comment by tiefenb** [comment]
I opend an isse at the offical php docker git repo: https://github.com/docker-library/php/issues/1283

**Comment by Justintime50** [comment]
Ah, if you're using the official image, then the issues you're facing are probably with the base image and not this Docker image. I hope the maintainers of the official image can provide some additional help!

I'm going to close this since you've reported the problem upstream.
